# Generated by Django 5.1.1 on 2024-11-08 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_logins', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login',
                'verbose_name_plural': 'User Logins',
                'db_table': 'UserLogins_TB',
            },
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('failed', models.BooleanField(default=False)),
                ('user_logins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='auth_module.userlogins')),
            ],
            options={
                'verbose_name': 'User IPs',
                'verbose_name_plural': 'User IP',
                'db_table': 'UserIP_TB',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('is_phone', models.BooleanField(default=False)),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('user_logins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='auth_module.userlogins')),
            ],
            options={
                'verbose_name': 'User Devices',
                'verbose_name_plural': 'User Device',
                'db_table': 'UserDevice_TB',
            },
        ),
    ]
